CREATE TABLE DROP TABLE IF EXISTS ODONTOLOGO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    matricula VARCHAR(100) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL
);
INSERT INTO ODONTOLOGO (matricula, nombre, apellido) VALUES ('1313', 'Juan', 'Sanchez');
SELECT * FROM ODONTOLOGO;